title: "Workshop on Autonomous Heavy Vehicles"
description: "A workshop focusing on autonomous off-road vehicle technologies."
baseurl: "" # Leave blank unless hosting in a subdirectory
url: "https://fatemeh-rastgar.github.io/autonomous-heavy-vehicles.github.io/"
theme: minima



<link rel="stylesheet" href="assets/style.css">
